ENH: Updated cosmic_gps to use public download option
pysat/pysatCDAAC pull request #17
Opened 2021-04-07 22:23 UTC by rstoneback

Addresses: #13 

Updates `cosmic_gps` to use the new public data server from CDAAC instead of the option that required authentication. Also turns on tests for `cosmic_gps`.

2021-04-07 22:26 UTC, rstoneback commented
@jklenzing - I believe there was some discussion about the sub-directory structure at one point. For this pull, I updated things to be `year/doy/file`. They were`year.doy/file`. It has been long enough for me that I don't remember if we talked about what to move to. What kind of improvement to directory structure are you talking about for #1?

2021-04-07 22:28 UTC, rstoneback commented
Requires #14 first

2021-04-08 13:59 UTC, jklenzing commented
> @jklenzing - I believe there was some discussion about the sub-directory structure at one point. For this pull, I updated things to be `year/doy/file`. They were`year.doy/file`. It has been long enough for me that I don't remember if we talked about what to move to. What kind of improvement to directory structure are you talking about for #1?

I think this should work. As I recall, the . Was giving me trouble

2021-04-08 15:01 UTC, rstoneback commented
I also tried to update the format_str to include parsing the year and day from the leading directories but that didn't work. It doesn't like leading or trailing keywords.

2021-04-08 20:09 UTC, rstoneback commented
Tested new file listing function on my machine with a bunch of GPS files.

```
In [1]: import pysat                                                                                                                                                      
g
In [2]: gps = pysat.Instrument('cosmic', 'gps', 'ionprf', update_files=True)                                                                                              

In [3]: gps.files.files                                                                                                                                                   
Out[3]: 
2009-01-01 00:12:00.125999872    2009.001/ionPrf_C001.2009.001.00.12.G26_2013.3...
2009-01-01 00:16:00.224000000    2009.001/ionPrf_C002.2009.001.00.16.G24_2013.3...
2009-01-01 00:17:00.209000192    2009.001/ionPrf_C002.2009.001.00.17.G09_2013.3...
2009-01-01 00:27:00.109999872    2009.001/ionPrf_C001.2009.001.00.27.G10_2013.3...
2009-01-01 00:28:00.212999936    2009.001/ionPrf_C002.2009.001.00.28.G13_2013.3...
2009-01-01 00:31:00.530999808    2009.001/ionPrf_C005.2009.001.00.31.G31_2013.3...
```

```
In [4]: len(gps.files.files)                                                                                                                                              
Out[4]: 2319390
```

2021-04-22 17:04 UTC, jklenzing commented
84.5% coverage! 👀

2021-04-30 01:23 UTC, rstoneback commented
Long lunch but I've expanded support to latest level-2 and level-1 files. I left out files with unknown type or content.

2021-05-03 18:35 UTC, jklenzing requested changes
Looking good.  Data loads and downloads as expected.  Fixing the "time mangling" of the uts time stamps is outside the scope here, but there should be something in the top-level docstring (either as a warning or a note) that uts is adjusted based on antenna number, etc.

2021-05-03 18:35 UTC, jklenzing commented on pysatCDAAC/instruments/cosmic_gps.py
> +_password_req = {'': {kk: False for kk in tags.keys()}}
```suggestion
```
Since these are the default value, they can be deleted.

2021-05-03 18:35 UTC, jklenzing commented on pysatCDAAC/instruments/cosmic_gps.py
> +        'gfsprf': ''}
We should have a basic description for each of these.

2021-05-03 18:35 UTC, jklenzing commented on pysatCDAAC/instruments/cosmic_gps.py
>  - 'ionprf: 'ionPrf' ionosphere profiles
```suggestion
- 'ionprf': 'ionPrf' ionosphere profiles
```

2021-05-03 18:35 UTC, jklenzing commented on pysatCDAAC/instruments/cosmic_gps.py
>  - 'ionprf: 'ionPrf' ionosphere profiles
Also, description of `tag` and `inst_id` should be updated on lines 21-25.

2021-05-26 22:54 UTC, rstoneback commented
Updates to time mangling are going to be handled in https://github.com/pysat/pysatCDAAC/pull/18. I referenced your review note about the docstring over there.

2021-05-26 23:26 UTC, jklenzing approved these changes

2021-05-27 00:01 UTC, merged